import type { Peptide, Product } from "./types";

export const peptides: Peptide[] = [
  {
    id: "pep_bpc157",
    slug: "bpc-157",
    name: "BPC-157",
    aka: ["Body Protection Compound"],
    category: "Tissue repair",
    summary:
      "A synthetic peptide fragment studied in preclinical settings for tissue repair signaling. Human evidence and regulatory status vary by country and indication.",
    researchStatus: "Preclinical",
    keyPoints: [
      "Often discussed in the context of repair pathways and gut-related models",
      "Commonly referenced in lab / preclinical literature rather than large human trials",
      "Handling and storage stability depend on formulation and vendor documentation",
    ],
    safetyNotes: [
      "Avoid medical claims and dosing guidance on-site; keep content informational",
      "Highlight batch documentation / COA workflows if you plan to provide them",
    ],
  },
  {
    id: "pep_cjc1295",
    slug: "cjc-1295",
    name: "CJC-1295",
    aka: ["GRF analog"],
    category: "Growth hormone axis",
    summary:
      "A peptide analog studied for effects on growth hormone signaling in research settings. Interpretation depends on study design and medical oversight.",
    researchStatus: "Early clinical",
    keyPoints: [
      "Frequently grouped with other GH-axis research compounds",
      "Users typically want fast access to “what it is / what it’s used for in studies / what to watch out for”",
      "Good candidate for cross-links: related peptides, comparisons, and product variants",
    ],
    safetyNotes: [
      "Keep regulatory/compliance copy clear; do not frame as treatment",
      "Prominent “educational” and “consult a professional” messaging is recommended",
    ],
  },
  {
    id: "pep_semaglutide",
    slug: "semaglutide",
    name: "Semaglutide",
    aka: ["GLP-1 receptor agonist"],
    category: "Metabolic",
    summary:
      "A GLP‑1 receptor agonist with approved pharmaceutical products in some markets. If you include it, separate educational content from any sales logic and follow local rules strictly.",
    researchStatus: "Approved drug (context-specific)",
    keyPoints: [
      "Clear separation of education vs. commerce is essential for trust and compliance",
      "Users will search synonyms and brand terms; alias handling matters",
      "A strong “status” badge reduces confusion (approved vs experimental)",
    ],
    safetyNotes: [
      "Do not provide medical advice or dosing; route people to clinicians",
      "Many platforms and payment providers restrict peptide sales; verify policies",
    ],
  },
];

export const products: Product[] = [
  // Снижение веса и метаболизм
  {
    id: "prd_001",
    slug: "tirzepatide-5mg",
    title: "Tirzepatide 5 mg",
    short: "Современный пептид для эффективного снижения веса и контроля аппетита",
    priceCents: 700000,
    currency: "RUB",
    image: "https://images.unsplash.com/photo-1576086213369-97a306d36557?auto=format&fit=crop&w=1200&q=80",
    category: "Снижение веса",
    tags: ["снижение веса", "аппетит", "популярное"],
    inStock: true,
  },
  {
    id: "prd_002",
    slug: "tirzepatide-10mg",
    title: "Tirzepatide 10 mg",
    short: "Современный пептид для эффективного снижения веса и контроля аппетита",
    priceCents: 1000000,
    currency: "RUB",
    image: "https://images.unsplash.com/photo-1576086213369-97a306d36557?auto=format&fit=crop&w=1200&q=80",
    category: "Снижение веса",
    tags: ["снижение веса", "аппетит", "premium"],
    inStock: true,
  },
  {
    id: "prd_003",
    slug: "retatrutide-5mg",
    title: "Retatrutide 5 mg",
    short: "Инновационный пептид для мощного снижения веса и контроля аппетита",
    priceCents: 900000,
    currency: "RUB",
    image: "https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?auto=format&fit=crop&w=1200&q=80",
    category: "Снижение веса",
    tags: ["снижение веса", "инсулин", "популярное"],
    inStock: true,
  },
  {
    id: "prd_004",
    slug: "aod9604-5mg",
    title: "AOD9604 5 mg",
    short: "Специализированный пептид для сжигания жира без влияния на сахар",
    priceCents: 500000,
    currency: "RUB",
    image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=1200&q=80",
    category: "Жиросжигание",
    tags: ["жиросжигание", "метаболизм", "безопасность"],
    inStock: true,
  },

  // Рост и восстановление
  {
    id: "prd_005",
    slug: "ipamorelin-cjc1295-10mg",
    title: "Ipamorelin + CJC-1295 10 mg",
    short: "Стимулятор гормона роста с минимальными побочными эффектами. Улучшает композицию тела и качество сна",
    priceCents: 750000,
    currency: "RUB",
    image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=1200&q=80",
    category: "Рост и восстановление",
    tags: ["рост", "сон", "популярное", "premium"],
    inStock: true,
  },

  // Иммунитет
  {
    id: "prd_006",
    slug: "thymosin-alpha1-10mg",
    title: "Thymosin Alpha-1 10 mg",
    short: "Мощный иммуномодулятор для укрепления защитных сил",
    priceCents: 900000,
    currency: "RUB",
    image: "https://images.unsplash.com/photo-1582719471384-894fbb16e074?auto=format&fit=crop&w=1200&q=80",
    category: "Иммунитет",
    tags: ["иммунитет", "детоксикация", "противовирусное"],
    inStock: true,
  },

  // Омоложение и кожа
  {
    id: "prd_007",
    slug: "glow-70mg",
    title: "Glow 70 mg",
    short: "Мультифункциональный пептидный комплекс для сияющей изнутри кожи",
    priceCents: 1500000,
    currency: "RUB",
    image: "https://images.unsplash.com/photo-1505944357431-c653a0e6d5a2?auto=format&fit=crop&w=1200&q=80",
    category: "Омоложение",
    tags: ["кожа", "коллаген", "популярное", "premium"],
    inStock: true,
  },
  {
    id: "prd_008",
    slug: "ghk-cu-50mg",
    title: "GHK-Cu 50 mg",
    short: "Медный пептид для омоложения кожи и восстановления тканей",
    priceCents: 450000,
    currency: "RUB",
    image: "https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?auto=format&fit=crop&w=1200&q=80",
    category: "Омоложение",
    tags: ["кожа", "коллаген", "заживление"],
    inStock: true,
  },
  {
    id: "prd_009",
    slug: "epithalon-10mg",
    title: "Epithalon 10 mg",
    short: "Геропротектор для замедления старения и восстановления циркадных ритмов",
    priceCents: 200000,
    currency: "RUB",
    image: "https://images.unsplash.com/photo-1584464491033-06628f3a6b7b?auto=format&fit=crop&w=1200&q=80",
    category: "Anti-age",
    tags: ["anti-age", "сон", "гормоны"],
    inStock: true,
  },

  // Регенерация
  {
    id: "prd_010",
    slug: "bpc157-10mg",
    title: "BPC-157 10 mg",
    short: "Революционный пептид для восстановления тканей и ускорения заживления",
    priceCents: 500000,
    currency: "RUB",
    image: "https://images.unsplash.com/photo-1576086213369-97a306d36557?auto=format&fit=crop&w=1200&q=80",
    category: "Регенерация",
    tags: ["восстановление", "жкт", "популярное", "premium"],
    inStock: true,
  },
  {
    id: "prd_011",
    slug: "bpc157-tb500-combo",
    title: "BPC-157 + TB-500 (5 mg + 5 mg)",
    short: "Смесь двух мощных регенеративных пептидов для максимального восстановления",
    priceCents: 600000,
    currency: "RUB",
    image: "https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?auto=format&fit=crop&w=1200&q=80",
    category: "Регенерация",
    tags: ["восстановление", "травмы", "комбо", "premium"],
    inStock: true,
  },
  {
    id: "prd_012",
    slug: "tb500-5mg",
    title: "TB-500 5 mg",
    short: "Мощный регенеративный пептид для восстановления мышц и связок",
    priceCents: 450000,
    currency: "RUB",
    image: "https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?auto=format&fit=crop&w=1200&q=80",
    category: "Регенерация",
    tags: ["восстановление", "суставы", "спорт"],
    inStock: true,
  },

  // Энергия и метаболизм
  {
    id: "prd_013",
    slug: "mots-c-10mg",
    title: "MOTS-C 10 mg",
    short: "Митохондриальный пептид, регулирующий метаболизм, энергию и стрессоустойчивость",
    priceCents: 500000,
    currency: "RUB",
    image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=1200&q=80",
    category: "Энергия",
    tags: ["энергия", "митохондрии", "выносливость"],
    inStock: true,
  },
  {
    id: "prd_014",
    slug: "nad-100mg",
    title: "NAD+ 100 mg",
    short: "Базовая дозировка коэнзима для начального использования и профилактики",
    priceCents: 800000,
    currency: "RUB",
    image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=1200&q=80",
    category: "Anti-age",
    tags: ["anti-age", "энергия", "память"],
    inStock: true,
  },
  {
    id: "prd_015",
    slug: "nad-500mg",
    title: "NAD+ 500 mg",
    short: "Средняя дозировка коэнзима для поддержания энергетического баланса",
    priceCents: 3200000,
    currency: "RUB",
    image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=1200&q=80",
    category: "Anti-age",
    tags: ["anti-age", "энергия", "премиум", "premium"],
    inStock: true,
  },
  {
    id: "prd_016",
    slug: "nad-1000mg",
    title: "NAD+ 1000 mg",
    short: "Максимальная дозировка коэнзима для полного курса восстановления",
    priceCents: 5000000,
    currency: "RUB",
    image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=1200&q=80",
    category: "Anti-age",
    tags: ["anti-age", "энергия", "курс", "популярное", "premium"],
    inStock: true,
  },

  // Либидо и гормоны
  {
    id: "prd_017",
    slug: "kisspeptin10-5mg",
    title: "Kisspeptin-10 5 mg",
    short: "Пептид для регуляции репродуктивной функции и гормонального баланса",
    priceCents: 600000,
    currency: "RUB",
    image: "https://images.unsplash.com/photo-1505944357431-c653a0e6d5a2?auto=format&fit=crop&w=1200&q=80",
    category: "Либидо",
    tags: ["либидо", "гормоны", "фертильность"],
    inStock: true,
  },
  {
    id: "prd_018",
    slug: "pt141-10mg",
    title: "PT-141 10 mg",
    short: "Инновационный пептид для усиления либидо через ЦНС",
    priceCents: 300000,
    currency: "RUB",
    image: "https://images.unsplash.com/photo-1576086213369-97a306d36557?auto=format&fit=crop&w=1200&q=80",
    category: "Либидо",
    tags: ["либидо", "быстрый эффект"],
    inStock: true,
  },

  // Нейропептиды
  {
    id: "prd_019",
    slug: "oxytocin-5mg",
    title: "Oxytocin 5 mg",
    short: "Нейропептид, отвечающий за привязанность, доверие и антистресс",
    priceCents: 300000,
    currency: "RUB",
    image: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1200&q=80",
    category: "Нейропептиды",
    tags: ["антистресс", "сон", "настроение"],
    inStock: true,
  },

  // Аксессуары
  {
    id: "prd_020",
    slug: "bactericidal-water-30ml",
    title: "Бактерицидная вода 30 мл",
    short: "Стерильная бактерицидная вода для разведения пептидов",
    priceCents: 250000,
    currency: "RUB",
    image: "https://images.unsplash.com/photo-1583911860205-72f8ac8ddcbe?auto=format&fit=crop&w=1200&q=80",
    category: "Аксессуары",
    tags: ["вода", "разведение", "необходимое"],
    inStock: true,
  },
];
