import type { Peptide, Product } from "./types";

export const peptides: Peptide[] = [
  {
    id: "pep_bpc157",
    slug: "bpc-157",
    name: "BPC-157",
    aka: ["Body Protection Compound"],
    category: "Tissue repair",
    summary:
      "A synthetic peptide fragment studied in preclinical settings for tissue repair signaling. Human evidence and regulatory status vary by country and indication.",
    researchStatus: "Preclinical",
    keyPoints: [
      "Often discussed in the context of repair pathways and gut-related models",
      "Commonly referenced in lab / preclinical literature rather than large human trials",
      "Handling and storage stability depend on formulation and vendor documentation",
    ],
    safetyNotes: [
      "Avoid medical claims and dosing guidance on-site; keep content informational",
      "Highlight batch documentation / COA workflows if you plan to provide them",
    ],
  },
  {
    id: "pep_cjc1295",
    slug: "cjc-1295",
    name: "CJC-1295",
    aka: ["GRF analog"],
    category: "Growth hormone axis",
    summary:
      "A peptide analog studied for effects on growth hormone signaling in research settings. Interpretation depends on study design and medical oversight.",
    researchStatus: "Early clinical",
    keyPoints: [
      "Frequently grouped with other GH-axis research compounds",
      "Users typically want fast access to “what it is / what it’s used for in studies / what to watch out for”",
      "Good candidate for cross-links: related peptides, comparisons, and product variants",
    ],
    safetyNotes: [
      "Keep regulatory/compliance copy clear; do not frame as treatment",
      "Prominent “educational” and “consult a professional” messaging is recommended",
    ],
  },
  {
    id: "pep_semaglutide",
    slug: "semaglutide",
    name: "Semaglutide",
    aka: ["GLP-1 receptor agonist"],
    category: "Metabolic",
    summary:
      "A GLP‑1 receptor agonist with approved pharmaceutical products in some markets. If you include it, separate educational content from any sales logic and follow local rules strictly.",
    researchStatus: "Approved drug (context-specific)",
    keyPoints: [
      "Clear separation of education vs. commerce is essential for trust and compliance",
      "Users will search synonyms and brand terms; alias handling matters",
      "A strong “status” badge reduces confusion (approved vs experimental)",
    ],
    safetyNotes: [
      "Do not provide medical advice or dosing; route people to clinicians",
      "Many platforms and payment providers restrict peptide sales; verify policies",
    ],
  },
];

export const products: Product[] = [
  {
    id: "prd_001",
    slug: "bpc-157-premium",
    title: "BPC-157 Premium",
    short: "Высокая чистота >99%, сертификат качества, быстрая доставка",
    priceCents: 8900,
    currency: "EUR",
    image: "https://images.unsplash.com/photo-1576086213369-97a306d36557?auto=format&fit=crop&w=1200&q=80",
    category: "Growth Hormone",
    peptideSlug: "bpc-157",
    tags: ["восстановление", "популярное", "premium"],
    inStock: true,
  },
  {
    id: "prd_002",
    slug: "tb-500-premium",
    title: "TB-500 Premium",
    short: "Для восстановления мышц и связок, чистота >98%",
    priceCents: 12900,
    currency: "EUR",
    image: "https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?auto=format&fit=crop&w=1200&q=80",
    category: "Recovery",
    tags: ["восстановление", "связки", "premium"],
    inStock: true,
  },
  {
    id: "prd_003",
    slug: "ipamorelin-premium",
    title: "Ipamorelin Premium",
    short: "Стимуляция гормона роста, без побочных эффектов",
    priceCents: 9900,
    currency: "EUR",
    image: "https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?auto=format&fit=crop&w=1200&q=80",
    category: "Growth Hormone",
    tags: ["рост", "ghrp", "premium"],
    inStock: true,
  },
  {
    id: "prd_004",
    slug: "cjc-1295-dac",
    title: "CJC-1295 with DAC",
    short: "Длительное действие, усиление выработки гормона роста",
    priceCents: 11900,
    currency: "EUR",
    image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=1200&q=80",
    category: "Growth Hormone",
    peptideSlug: "cjc-1295",
    tags: ["рост", "grf", "premium"],
    inStock: true,
  },
  {
    id: "prd_005",
    slug: "mk-677-premium",
    title: "MK-677 (Ibutamoren)",
    short: "Усиление секреции GH и IGF-1, улучшение сна",
    priceCents: 7900,
    currency: "EUR",
    image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=1200&q=80",
    category: "Performance",
    tags: ["сон", "восстановление", "популярное"],
    inStock: true,
  },
  {
    id: "prd_006",
    slug: "ghrp-6-premium",
    title: "GHRP-6 Premium",
    short: "Стимуляция аппетита и выработки GH, для набора массы",
    priceCents: 8400,
    currency: "EUR",
    image: "https://images.unsplash.com/photo-1584464491033-06628f3a6b7b?auto=format&fit=crop&w=1200&q=80",
    category: "Growth Hormone",
    tags: ["аппетит", "масса", "ghrp"],
    inStock: true,
  },
  {
    id: "prd_007",
    slug: "melanotan-2",
    title: "Melanotan II",
    short: "Пептид для загара и либидо",
    priceCents: 6900,
    currency: "EUR",
    image: "https://images.unsplash.com/photo-1505944357431-c653a0e6d5a2?auto=format&fit=crop&w=1200&q=80",
    category: "Performance",
    tags: ["загар", "либидо"],
    inStock: true,
  },
  {
    id: "prd_008",
    slug: "peptide-starter-kit",
    title: "Стартовый набор",
    short: "Все необходимое для начала: шприцы, вода, спирт",
    priceCents: 2490,
    currency: "EUR",
    image: "https://images.unsplash.com/photo-1583911860205-72f8ac8ddcbe?auto=format&fit=crop&w=1200&q=80",
    category: "Lab supplies",
    tags: ["набор", "для начинающих", "starter"],
    inStock: true,
  },
];
